### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Tcll** [pericazivkovic/portablepython#19]
basically, I'm including the interpreter with my distribution...
(I have an EXE which acts as a BAT to start from the x86 or x64 interpreters)
^ my program also adjusts itself based on your CPU, so it knows if it topps out or not

I'd like to be able to distribute my program on the linux platform as well...
(I have a few testers who can't run it because of this)

**Comment by Tcll** [comment]
and there's also the fact that SteamOS is Linux based,
which I intend to start development on once I get it.

**Comment by pericazivkovic** [comment]
no linux support planned, sorry. Most linux distros come with python already,
