### ISSUE TITLE
Binary files under /tools aren't on repository (used by build.bat)

### ISSUE THREAD

**Issue by fgmacedo** [pericazivkovic/portablepython#5]
Hi, first congrats for your great work with PortablePython!

I'm trying to play with your build scripts, but it is taking a while because the .exe binaries used by _build.bat_ aren't versioned.

It'll be great do automatize the necessary setup, or to have those files under version control.

Best regards,

**Comment by pericazivkovic** [comment]
o wow that is a good catch ! thank you I will add the files my intention was to have everything in the repo

**Comment by pericazivkovic** [comment]
Files added!

**Comment by fgmacedo** [comment]
It worked. Thanks!
