### ISSUE TITLE
Disable splash screen

### ISSUE THREAD

**Issue by cfobel** [pericazivkovic/portablepython#7]
Is it possible to disable the Portable Python splash screen?  I would be willing to donate to the project, but would like to distribute an application running using Portable Python, and would like to use my own splash screen for branding.

**Comment by pericazivkovic** [comment]
It is possible of-course, all source is available so you can do it if you fork this repository and customise however you want. 
- To disable go to: `shortcuts/shortcut.nsi` and modify or comment out `Function SplashLogo` part
- To customise you could modify `shortcuts/splashX.X.bmp` where X.X is version you want to build with your own branded splash image. When you run build next time, all shortcuts will have your embedded splash image.

**Comment by cfobel** [comment]
Awesome, thanks!  I did try looking through the code, but am not familiar
the installer used here and couldn't find the relevant section.  Thanks
again for pointing me in the right direction.

**Comment by methanoid** [comment]
Would be better if the project allowed a "DisplaySplashScreen=false/true" like most other portable apps... I run about 5 Python apps on startup and my login is bombarded with Portable Python splash screens ;-) Don't want to fork and rebuild all just to do what most portable apps do.... ;-)

**Comment by nmz787** [comment]
Any work on this being disabled without recompiling (which isn't working for me, so I've been using the pre-built binaries)?

**Comment by pericazivkovic** [comment]
Could you help me understand why is recompiling not working?

Indeed it is better to have config file like with portable apps and I'm looking into it!
